### ISSUE TITLE
String  In conversion occur data lost

### ISSUE THREAD

**Issue by tomatopunk** [paulyoder/LinqToExcel#150]
Raw data Length total is 636
Converted to memory Obj Length total is 424
 
Can you configure this restriction?
How to solve my question

**Comment by mrworkman** [comment]
I'm not sure to what you are referring. I need more details.

**Comment by mrworkman** [comment]
Hmmm, might be a limitation in the db driver. Unfortunately I won't have time to look into it for awhile. So I can't promise anything :(

**Comment by sfjadi2010** [comment]
Hi, Can you give me some directions? So, I can look and debug this issue?

-Salman
________________________________

**Comment by mrworkman** [comment]
I am not able to reproduce the issue you are seeing (as far as I understand it). I created a worksheet that has a column that contains over 7000 characters in one of its cells, and I was able to read every character out of it...

Please provide the following details:
1. Version of LinqToSql
1. Is your application 32, or 64 bit?
1. Version of Windows
1. Windows region information (e.g. format "English (United States)")
1. Whether you are using the Microsoft ACE database engine, and its version.

Also, if you can provide a sample of the code you're using that results in the behaviour you've described, that would be helpful. Additionally if you could re-create the issue in a similar workbook, and attach that here, that would also be very helpful.

**Comment by AbbasNarimani** [comment]
Hi. I have the same problem. If you want to reproduce the issue, you should make an excel file with more than 8 rows and put your long text in the last row. this problem happens because of OLEDB's type guessing which by default, looks at the first 8 rows and decides which type it is. if the first 8 rows were shorter than 255 characters it would truncate the rest of rows.
+My LinqToSql version is 1.11.0
+My application is 64 bit
+Windows 10 pro

**Comment by tomatopunk** [comment]
is end,closed
